name: Akhenaten Build Mac

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: run on mac arm64
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/cache@v4
      id: cache-sdl-libs
      with:
        path: |
          ~/Library/Frameworks/SDL2.framework
          ~/Library/Frameworks/SDL2_image.framework
          ~/Library/Frameworks/SDL2_mixer.framework
        key: ${{ runner.os }}-download-sdl-arm64-${{ hashFiles('./.ci-scripts/mac/download-sdl.sh') }}

    - name: download-sdl
      if: steps.cache-sdl-libs.outputs.cache-hit != 'true'
      run: ./.ci-scripts/mac/download-sdl.sh

    - name: update-workspace
      run: |
        mkdir -p build
        cd build
        export CXXFLAGS=-stdlib=libc++
        cmake -DCMAKE_OSX_DEPLOYMENT_TARGET=11.7 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_OSX_ARCHITECTURES="arm64" -DOPTION_SYSTEM_LIBPNG=OFF -DOPTION_BUILD_LIBPNG=ON .. -G "Unix Makefiles"
        cd ..

    - name: build
      run: |
        cmake --build ./build -j6

    - name: install-and-bundle
      run: |
        cmake --build ./build --target install/local
        mkdir macos_build
        cp -R ./build/akhenaten.app ./macos_build/akhenaten.app

    - uses: actions/upload-artifact@v4
      with:
        name: macos_build
        path: macos_build
