name: Akhenaten Build Mac

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: run on mac arm64
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install OpenSSL (for curl)
      run: brew install openssl@3
    - name: update-workspace
      run: |
        mkdir -p build
        cd build
        export CXXFLAGS=-stdlib=libc++
        export OPENSSL_ROOT_DIR=$(brew --prefix openssl@3)
        cmake -DCMAKE_OSX_DEPLOYMENT_TARGET=11.7 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_OSX_ARCHITECTURES="arm64" -DOPTION_SYSTEM_LIBPNG=OFF -DOPTION_BUILD_LIBPNG=ON -DCMAKE_INSTALL_PREFIX="$PWD/install" .. -G "Unix Makefiles"
        cd ..

    - name: build
      run: |
        cmake --build ./build -j6

    - name: install-and-bundle
      run: |
        cmake --build ./build --target install/local
        mkdir macos_build
        cp -R ./build/install/akhenaten.app ./macos_build/akhenaten.app

    - uses: actions/upload-artifact@v4
      with:
        name: macos_build
        path: macos_build
